// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ5Iu-NiSzduzk7r7aloaObyxhpiiFSKo',
    appId: '1:819952879259:web:ee70511ca693ac82a7283e',
    messagingSenderId: '819952879259',
    projectId: 'chatflutterapp-e8d86',
    authDomain: 'chatflutterapp-e8d86.firebaseapp.com',
    storageBucket: 'chatflutterapp-e8d86.appspot.com',
    measurementId: 'G-RSCQPTX8NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDisiloHhOoXtPHpZ0ReaxgAaCC513AWpM',
    appId: '1:819952879259:android:b56e601c20c33a2ba7283e',
    messagingSenderId: '819952879259',
    projectId: 'chatflutterapp-e8d86',
    storageBucket: 'chatflutterapp-e8d86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA96letRGU6x1y6wTbrUhmXL1Rnc72Yo1s',
    appId: '1:819952879259:ios:8f784da08a02b6d7a7283e',
    messagingSenderId: '819952879259',
    projectId: 'chatflutterapp-e8d86',
    storageBucket: 'chatflutterapp-e8d86.appspot.com',
    iosClientId: '819952879259-pai38lui7mrlvvirvstvte6h0vgtrku2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA96letRGU6x1y6wTbrUhmXL1Rnc72Yo1s',
    appId: '1:819952879259:ios:c8c7b8d27f47e3bea7283e',
    messagingSenderId: '819952879259',
    projectId: 'chatflutterapp-e8d86',
    storageBucket: 'chatflutterapp-e8d86.appspot.com',
    iosClientId: '819952879259-hie8lf3dh8bpmqhg5qu4guvg22b7o351.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
