name: chat_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.4
  google_sign_in: ^6.1.4
  firebase_auth: ^4.7.2
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
